# This is a DivSeek Canada customized version of the
# docker-tripal sample configuration to run a Tripal instance with Docker-Compose
#
# We assume here that we have created a (host user owned) /Volumes/DivSeekCanada directory
# with created (but empty) subdirectories 'tripal_sites', 'tripal_private', 'tripal_db' and 'tripal_index'
#
# This configuration assumes a Mac OSX kind of "/Volumes/" location, but
# this value may be adjusted under other operating systems.
# See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for ideas on how to customize this further (on Mac)
# or see the corresponding documentation for other operating systems versions of Docker.
#
# These (sub)directories will serve as the locations external to the docker containers
# within which the Tripal instance will store its (meta)data, for easy external backup (and direct access)
#
# For example, the /Volumes/DivSeekCanada/tripal_sites directory contains the 'sites' configuration of Tripal (Drupal)
# which may be iteratively modified to customize the site.
#

version: '3'
services:

    web:
      image: quay.io/erasche/tripal:v3.x
      volumes:
      - /Volumes/DivSeekCanada/tripal_sites:/var/www/html/sites
      - /Volumes/DivSeekCanada/tripal_private:/var/www/private
      environment:
        UPLOAD_LIMIT: 20M
        MEMORY_LIMIT: 128M
        BASE_URL: "http://localhost:3000/tripal"
        BASE_URL_PROTO: "http://"
        DB_NAME: 'postgres'
        SITE_NAME: "DivSeek Canada"
        THEME: "garland"
      ports:
        - "3000:80"
      depends_on:
      - db
      - elasticsearch
      networks:
      - default

    db:
      image: erasche/chado:1.31-jenkins97-pg9.5
      environment:
        - POSTGRES_PASSWORD=postgres
          # The default chado image would try to install the schema on first run,
          # we just want the tools to be available.
        - INSTALL_CHADO_SCHEMA=0
        - INSTALL_YEAST_DATA=0
        - PGDATA=/var/lib/postgresql/data/
      volumes:
      - /Volumes/DivSeekCanada/tripal_db:/var/lib/postgresql/data/
      networks:
        default:
          aliases:
          - postgres

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
      environment:
        TAKE_FILE_OWNERSHIP: "true"
      volumes:
      - /Volumes/DivSeekCanada/tripal_index/:/usr/share/elasticsearch/data
      networks:
      - default

networks:
  default:
    driver: bridge
